services:
  app-htql:
    container_name: htqlbenhvien-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db-htql
    ports:
      - "3005:3000"
    networks:
      - htql-prod-network

  db-htql:
    container_name: htqlbenhvien-db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - htql-prod-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - htql-prod-network

  nginx-prod:
    image: nginx:alpine
    container_name: htqlbenhvien-nginx-prod
    restart: always
    # ports:
    #  - "3001:3001" # Cổng này đang bị global-nginx chiếm, nên tắt đi để khỏi báo lỗi
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount chứng chỉ SSL từ máy chủ vào
    depends_on:
      - app-htql
    networks:
      - htql-prod-network

networks:
  htql-prod-network:
    driver: bridge

volumes:
  htql-prod-data:
