events {
    worker_connections 1024;
}

http {
    client_max_body_size 50M;

    server {
        # Đọc HTTPS qua cổng 3001 (hoặc cổng mà Docker đang expose)
        listen 3001 ssl;
        server_name htqlbenhvien.bvdklangson.com.vn;

        # Trỏ đến file chứng chỉ Let's Encrypt được mount từ máy chủ vào
        ssl_certificate /etc/letsencrypt/live/htqlbenhvien.bvdklangson.com.vn/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/htqlbenhvien.bvdklangson.com.vn/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            # Proxy vào app NextJS nội bộ
            proxy_pass http://app-htql:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
