events {
    worker_connections 1024;
}

http {
    client_max_body_size 50M;

    server {
        # Đọc HTTP qua cổng 3001 (vì SSL đã được Nginx ngoài xử lý)
        listen 3001;
        server_name htqlbenhvien.bvdklangson.com.vn;

        # Redirect root to /htqlbenhvien
        location = / {
            return 301 /htqlbenhvien;
        }

        location / {
            # Proxy vào app NextJS nội bộ
            proxy_pass http://app-htql:3000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        # Bổ sung: Hỗ trợ các lời gọi fetch('/api/...') bị hardcode ở frontend
        location /api/ {
            proxy_pass http://app-htql:3000/htqlbenhvien/api/;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
